### PR TITLE
V0.3+

### PR DESCRIPTION
**Pull request by fosspill**
- [x] Storable configuration for important directories
- [x] Backup and restore of important game files
- [x] Manage mods (enable / disable) 
- [x] Update usage guide
- [x] Create binaries

- [x] Update website version variable

### CODE REVIEW

**Comment by fosspill** [comment]
#31 will be pulled to update version number as new version is released.

**Comment by fosspill** [comment]
@CodeLingoBot review

**Comment by fosspill** [comment]
@shinnova if you click "Details" above you can see issues fixed and made with this PR.

Also, I started a changelog draft at https://github.com/fosspill/FFXIV_TexTools_CLI/releases/tag/untagged-4333cad20587caa57fa6 . Could you verify that it looks alright? 🍡

**Comment by shinnova** [comment]
The changelog looks correct. Nothing is missing either. :+1:

**Pull request merged**
